name: Fix PHP code style issues

on:
  push:
    paths:
      - '**.php'

jobs:
  php-code-styling:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
          ref: ${{ github.head_ref }}

      - name: Fix PHP code style issues
        uses: aglipanci/laravel-pint-action@2.1.0

      -   name: Extract branch name
          shell: bash
          run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          id: extract_branch

      -   name: Commit changes
          uses: stefanzweifel/git-auto-commit-action@v4.16.0
          with:
            commit_message: Fix styling
            branch: ${{ steps.extract_branch.outputs.branch }}
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
